# Generated by Django 4.1.7 on 2023-03-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
