# Generated by Django 4.1.7 on 2023-03-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_user_email_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
    ]
